### ISSUE TITLE
Error: 'scripts' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Jero786** [therealklanni/git-guppy#1]
Hi! i try to use your module but when I try to install, throw the exception:

'scripts' is not recognized as an internal or external command,
operable program or batch file.

3583 info postuninstall git-guppy@0.2.1
3584 error git-guppy@0.2.1 postinstall: `scripts/install.js`
3584 error Exit status 1
3585 error Failed at the git-guppy@0.2.1 postinstall script.
3585 error This is most likely a problem with the git-guppy package,
3585 error not with npm itself.
3585 error Tell the author that this fails on your system:
3585 error     scripts/install.js
3585 error You can get their info via:
3585 error     npm owner ls git-guppy
3585 error There is likely additional logging output above.
3586 error System Windows_NT 6.2.9200
3587 error command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "git-guppy"
3588 error cwd c:\Users\Jerónimo\gulp-test1
3589 error node -v v0.10.31
3590 error npm -v 1.4.23
3591 error code ELIFECYCLE
3592 verbose exit [ 1, true ]

------------------
My local env:
-------------------
Win 8.1
node v0.10.31
npm 1.4.23
gulp CLI: 3.8.7 / Local Version: 3.8.8

**Comment by viveleroi** [comment]
We've been bitten by this too. Half the team is on Windows and after looking into it, it's clear windows thinks "scripts/install.js" is a command and tries to execute it - erroring out. It doesn't realize it's a script to execute which is why `node scripts/install.js` works. 

However, there's no reasonable way to modify that unless you're willing to change it in the source.

Because the installation errors out, npm removes the directory entirely and there's no way to manually run that script either.

I think for now we'll just have to settle for a custom commit hook.

**Comment by therealklanni** [comment]
@viveleroi please take a look at and try out [v1.0](https://github.com/therealklanni/git-guppy/tree/1.0). I have no tested it on Windows, but it doesn't rely on the install script, so you may have better luck. As a bonus, it's very feature-complete and has a much nicer interface (almost ready for release).

Until I finish up a last few tasks needed before publishing to npm, you can add it to your package.json like so:

```js
"devDependencies": {
  "git-guppy": "git+https://github.com/therealklanni/git-guppy#1.0"
}
```

Please let me know if this solves your problem!

**Comment by viveleroi** [comment]
Thanks! Not sure yet if I'll have a chance to test 1.0. For this project I think we'll just do a pre-commit that runs a gulp command but I'm not sure how that works on windows either.

Personally, most of my work/team are all on Mac, so outside this one project it's not a huge issue for me.

I'll be eager to try 1.0 for my own stuff though!

**Comment by therealklanni** [comment]
See #12

**Comment by yearegods** [comment]
I just had this same issue.  'scriptcs' is not recognized as an internal or external command,
operable program or batch file.

Did you publish the v1.0 yet?  Do I need to do an npm install to get it working?  the link to the v1.0 is also dead

**Comment by therealklanni** [comment]
What version of guppy are you using? v2.1.0 is the latest.

**Comment by Divya063** [comment]
On installing git-guppy on windows it is showing an error
![screenshot 210](https://user-images.githubusercontent.com/21216969/29302139-42f30042-819f-11e7-9a81-03e1b922a290.png)

**Comment by therealklanni** [comment]
@Divya063 sorry you're having trouble, but it looks like your issue is maybe unrelated to this thread? Can you copy/paste the full error text into a new GitHub issue? Thanks!
