### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by filidorwiese** [therealklanni/git-guppy#12]
Yesterday I've succesfully installed Guppy into our workflow to enforce unit-test/linting on commit. Sadly it turns out that there is no Windows support for this plugin. One of our teammembers who is on WIndows now can't commit anymore, so I'll have to remove Guppy again... Is there any chance Windows will be supported in the near future?

**Comment by therealklanni** [comment]
@filidorwiese my apologies. I don't have Windows, so I can't test. If you can post any errors your coworker is getting, that would be helpful.

If you can identify the problem and want to submit a patch, please do. Otherwise, your coworker can always skip the pre-commit hook and just run the gulp tasks manually.

Windows support is very low priority right now. The main priority now is getting to v1. I hope to be able to support Windows in the future.

**Comment by filidorwiese** [comment]
I personally don't use Windows either so I can't tell you exactly where it went wrong. Our team has decided to go for a manual git-commit hook. What I do know though is that when Guppy is used within a GUI git-client (for example SourceTree or Tower) on MacOSX there are some path problems, these can be solved by adding this line to the commit hook:

```
PATH=$PATH:/usr/local/bin;/usr/local/sbin
```

**Comment by therealklanni** [comment]
Thanks for the info!

**Comment by olafura** [comment]
https://github.com/therealklanni/guppy-cli/pull/1
https://github.com/marcellodesales/git-guppy-pre-commit-hook/pull/2

There wasn't a lot of things wrong, I tested it on a virtual machine and worked out the kinks.

**Comment by therealklanni** [comment]
Regarding marcellodesales/git-guppy-pre-commit-hook#2, this code isn't merge with git-guppy or guppy-cli, so I'm not sure what your intent was with that.

**Comment by olafura** [comment]
Thanks, we'll start using the guppy-pre-commit, seems like very clean solution.

**Comment by therealklanni** [comment]
The guppy-pre-commit package needs to be republished to use guppy-cli 0.3.0, but I won't have time to update it until after work today, just FYI.

**Comment by therealklanni** [comment]
All hook installer packages are now updated and git-guppy should therefore support Windows now! :metal:
