### ISSUE TITLE
Make Git hooks optional

### ISSUE THREAD

**Issue by samvv** [therealklanni/git-guppy#2]
I have a minor suggestion that might make guppy more user-friendly: when using it for small projects, it is often not necessary to configure all hooks, and leaving an empty task like this:

````javascript
gulp.task('pre-rebase', [ 'test' ], function() {});
````

just adds extra code to the Gulpfile that makes it more difficult to read/maintain.

Often, when an author does not define a specific task for a specific hook this means the author is not expecting the hook to do anything, so it makes sense to not require any hook to be defined by default.

Does this sound like a good idea?

**Comment by therealklanni** [comment]
This is resolved for future 1.0 release (see [1.0 branch](https://github.com/therealklanni/git-guppy/tree/1.0) for details).
