### ISSUE TITLE
Git-Guppy pre-commit hook with Gulp

### ISSUE THREAD

**Issue by asadsahi** [therealklanni/git-guppy#32]
I have installed git-guppy package using:

```
npm i git-guppy --save-dev
```

Package is installed, but can't see the pre-commit hook script in .git/hooks folder of my project. 
Here are the files in .git/hooks folder after git-guppy package installation:

![unnamed](https://cloud.githubusercontent.com/assets/3470892/8024110/fa7d179e-0d1f-11e5-936d-117dcbd95735.png)

Question 1: Does git pre-commit hook script installed as part of git-guppy pakage?

Next, setup guppy:

```js
var gulp = require('gulp');
var guppy = require('git-guppy')(gulp);

and defined a gulp task:

gulp.task('pre-commit', ['vet']); // vet is a task which runs jscs and jshint on my code
```

I am lost from here. Not sure what have I missed/or do to run "vet" task. Checkin isn't running this task.

**Comment by therealklanni** [comment]
There are 2 ways you can install the pre-commit hook:

#### Manually:

```
npm install -g guppy-cli
guppy pre-commit
```

This will install a pre-commit hook for guppy in the current repository.

#### Auto installer (good for redistributable packages):

```
npm install --save-dev guppy-pre-commit
```

**Comment by asadsahi** [comment]
Thanks, worked like a charm +1
