### ISSUE TITLE
Update guppy-commit-msg package for new guppy-cli version

### ISSUE THREAD

**Issue by vasily-shakhov** [therealklanni/git-guppy#35]
Current version in npm needs update like guppy-pre-commit was updated

**Comment by therealklanni** [comment]
Sorry, I'm not sure what you're asking, can you please explain in more detail?

**Comment by vasily-shakhov** [comment]
Sorry if i wrote unclear.

There is package https://www.npmjs.com/package/guppy-pre-commit for pre-commit hook. It wonderful and works nicely. It has version 0.2.1.

There is package https://www.npmjs.com/package/guppy-commit-msg for commit-message hook. 
It has version 0.1.0 and don't work right after installing. 

If i go to .git/hooks and replace content if commit.msg file with content from pre-commit file all works correctly.

Can u please update https://www.npmjs.com/package/guppy-commit-msg package so it will work in the same way as guppy-pre-commit?

**Comment by therealklanni** [comment]
Please open an issue on guppy-commit-msg, then. This is not the appropriate repo for reporting an issue with guppy-commit-msg.

Thanks.
