### ISSUE TITLE
commit never stops

### ISSUE THREAD

**Issue by DemidovVladimir** [therealklanni/git-guppy#37]
I have meteor app and gulp folder with all gulp files right in ./.gulp
I have pre-commit and prepare-commit-msg hooks from your guppy...
I want to check my indexed files with lint... Thus I have to do:

```js
var errorReporter = function errorReporter () {
    return map(function (file, cb) {
        if (!file.jshint.success) {
            jungle();
            cb(new Error('something bad happened'));
        }
        cb(null, file);
    });
};

gulp.task('pre-commit', guppy.src('pre-commit', function (filesBeingCommitted) {
// this works fine with proper files
    return gulp.src('../' + filesBeingCommitted)
        .pipe(gulpFilter(['*.js']))
        .pipe(jshint('.jshintrc'))
        .pipe(jshint.reporter('jshint-stylish'))
        .pipe(errorReporter())
        .pipe(jshint.reporter('fail'));
}));
```

After adding proper files to git, I'm doing `git commit --amend`. 

I have a lot of errors printed on my terminal window. But even after that, everything getting committed. Why? 
I need to stop committing changes if errors occured. Is it possible with your hooks?

**Comment by DemidovVladimir** [comment]
Looked at pre-hook and it has to work proper.

**Comment by therealklanni** [comment]
Yeah, it absolutely should stop the commit, unless you did `git commit --no-verify`. 

In order for the commit to fail (not continue committing) the gulp task has to exit with non-zero status. This is a Unix concept, when a program exits it exists with status `0` meaning no errors, anything other than `0` means an error occurred—if your gulp task doesn't exit with a non-zero status, git will not know to stop the commit.

A way you can test this is to `git add` some files that with *purposefully* fail the JSHint task you have, and then, rather than try to `git commit` just run `gulp pre-commit` and check the exit code (`echo $?`). It should say `1` or anything other than `0`. If it says `0` then gulp is not exiting properly when JSHint has an error.

**Comment by DemidovVladimir** [comment]
Thanks, I’ve tried that way and I totally understand how does processes work in nodejs, but that is not working. I even tried to shut down the process directly in my custom piped function.
Made it with process.exit(1) even with process.kill(pid, ’SIGINT’)
But the result is the same.
Ok, I will try ti deal with it some how.

**Comment by DemidovVladimir** [comment]
Hello,
It exits with 1, I forgot to wright. But the process goes further and git is doing commit.
Strange!

**Comment by DemidovVladimir** [comment]
What should I do?

**Comment by DemidovVladimir** [comment]
https://github.com/DemidovVladimir/devops

**Comment by DemidovVladimir** [comment]
'pre-commit' errored after 109 ms
This is the answer after gulp pre-commit
But nothing stops after git commit --amend
Why is that? Please contact me ASAP, I've passed 2 days for that stupid bug and still don't know how to deal with it...

**Comment by DemidovVladimir** [comment]
I've even changed the hook.kill to hook.kill('SIGINT');

**Comment by DemidovVladimir** [comment]
The problem is in your guppy.src() it returns empty array only with hooks but when you're doing gulp pre-commit it returns ['server/app.js']... Strange behaivior... I've made static addresses and everithing works fine... Try to deal with it or give people info... For me it cost 2 - 3 days of maintaining!

**Comment by therealklanni** [comment]
@DemidovVladimir I understand you're frustrated, but you're the only person that has ever reported this issue. Most likely it's a problem with how your gulp script is written. Can you try removing (comment) this line and try it again? You shouldn't need to use any custom errorHandler, `jshint.reporter('fail')` already handles this for you.

```js
        .pipe(errorReporter())
```

Also it would be a good idea to post which version of each tool you're using (gulp, git-guppy, gulp-jshint) as well as copy/paste the actual output of `gulp pre-commit` so I can see exactly what is really happening.

Additionally, `filesBeingCommitted` is an array, but you are trying to concat that onto a string (`"../"`), which means the array will be coerced to a string. E.g. `"../" + ['file1', 'file2'] === "../file1,file2"`, make sense? Instead try doing a transform on the array using `Array#map` or some such before passing it to `gulp.src`. 

> Note: if `filesBeingCommitted` has 0-1 elements in the array, that sort of concatenation works fine, but when there are more than 1 elements, it will concatenate wrong as in my above example.

Lastly, you probably want to use `guppy.stream` with pre-commit instead. Please refer to the README.

**Comment by therealklanni** [comment]
Closing due to no response.

**Comment by hackhat** [comment]
Hi!
I'm also having the same issue.

```
  gulp.task('pre-commit', ['eslint']);
  gulp.task('eslint', () => {
    return gulp.src([
      './*.js',
      'src/**/*.js',
      'test/**/*.js',
      '!node_modules/**',
      '!build/**',
      '!docs/**',
      '!test/__notUsed**',
      '!test/clientIntegration/coverage/**',
      '!test/clientUnit/coverage/**',
    ])
      .pipe(eslint())
      .pipe(eslint.format());
  });
```

Event if eslint fails it stills commit:

	"C:\Program Files\Git\bin\git.exe" commit --amend -F "C:\X\dev\X\.git\COMMITMESSAGE"
	[23:10:49] Using gulpfile C:\X\dev\X\gulpfile.js
	[23:10:49] Starting 'eslint'...
	[23:10:52] 
	C:\X\dev\X\test\e2e\src\features\step_definitions\browser_steps.js
	  17:32  error  Missing trailing comma  comma-dangle

	✖ 1 problem (1 error, 0 warnings)

	[23:10:52] Finished 'eslint' after 3.08 s
	[23:10:52] Starting 'pre-commit'...
	[23:10:52] Finished 'pre-commit' after 23 μs
	[end-to-end-testing 7cf47f2] Ignore commit
	 Date: Thu Sep 15 23:05:49 2016 +0100
	 1 file changed, 1 insertion(+)
	Done

As you can see there is an error in the eslint task, but it still commits. Even without amend. I'm using git extensions as  git gui.

**Comment by therealklanni** [comment]
@hackhat you need to add `eslint.failAfterError()`. Please review the [gulp-eslint docs](https://github.com/adametry/gulp-eslint).
