### ISSUE TITLE
Git sub modules

### ISSUE THREAD

**Issue by mikevalstar** [therealklanni/git-guppy#39]
when attempting to install guppy hooks into a git submodule you will get an error like: 

        fatal: ENOTDIR: not a directory, mkdir '/projects/example/example-sub/.git/hooks'

this is because it is not a folder but a .git file. contents: 

        gitdir: ../.git/modules/example-sub

he install script should detect this and use the value of the file to know where to create the folder and file(s). in this case: ../.git/modules/example-sub/hooks/

**Comment by therealklanni** [comment]
Need to update the guppy-cli dependency to 0.4.0

**Comment by therealklanni** [comment]
Updated and published git-guppy v1.0.1
