### ISSUE TITLE
plugin does not work if gulpfile and git repository are not in the same folder

### ISSUE THREAD

**Issue by pavel06081991** [therealklanni/git-guppy#41]
Hello. We chose your gulp plugin git-guppy for our project. I installed guppy-pre-commit package and git-guppy. All work good when your git repository and gulpfile are in the same folder, for examples:
```javascript
.git/
gulpfile.js
node_modules/
package.json
```

but when git repository is in another folder I get the next error message after commiting: Local gulp not found in D:\work\projects\myProject

here is the files structure:
```javascript
myProject/
   .git/
   someFolder1/
      someFolder2/
         gulpfile.js
         node_modules/
         package.json
```
How can I fix this problem? Thanks.

**Comment by therealklanni** [comment]
Thanks. I'll try to reproduce it and try to find a solution.

**Comment by therealklanni** [comment]
I just published git-guppy v1.0.1 which fixes a similar issue. Please try updating your git-guppy to the latest version and let me know if you're still experiencing the issue.

**Comment by pavel06081991** [comment]
Unfortunately the problem still exists.

**Comment by therealklanni** [comment]
OK, thanks for trying. I am still trying to reproduce it.

**Comment by therealklanni** [comment]
Hi @pavel06081991, sorry about the wait. I don't think I'm going to be able to resolve this. This is just a very edge case, and unfortunately guppy is very closely tied with both gulp and git, so it's pretty much a requirement that the project is in the same root as the git root.

**Comment by pavel06081991** [comment]
Okay, thanks. Unfortunately I can not change project files structure. But anyway thanks :)

**Comment by robianmcd** [comment]
I'm running into the same problem. Guess I'll have to use something like gulp-chug and maintain two seperate gulpfile.js/package.json files.
