### ISSUE TITLE
Modular Architecture Proposal

### ISSUE THREAD

**Issue by marcellodesales** [therealklanni/git-guppy#7]
As described at the deferred issue #6, the architecture of git-guppy should be modular instead of static: users would install the basic git-guppy without the hooks and install each individual set of modules separately using npm -i as usual.

*Proposal: Separate this project as the "core" git-guppy and create multiple git-guppy-HOOK_GROUP for the different hooks, following Git's docs.* 

Here's what we could do to get this quickly done.

 * Git-guppy-core does not install anything by default: 

Make the lib/gitHooks.json list empty, so that installing git-guppy would not install anything.

 * Create groups of related git-guppy-HOOK_GROUP modules where:

Each group would have the lib/gitHooks.json file with the list of related hooks.

 * Git-guppy-core installs each git-guppy-HOOK_GROUP module from the APP.

Needs to retrieve the list of any installed "git-guppy-HOO_GROUP" module by reading the APP's package.json, iterating over all the `dependencies`/`devDependencies` searching for "git-guppy-HOOK_GROUP".

For each of the installed ones, retrieve the lib/gitHooks.json with the list of hooks to install, and execute the same procedures to install today.

**Comment by therealklanni** [comment]
No longer relevant, as 1.0 implements this.

**Comment by lucasconstantino** [comment]
Hi, there!

Why couldn't we just add a property to the project's package.json identifying implemented hooks? Is there any issue with this kind of model?

**Comment by therealklanni** [comment]
@lucasconstantino hello there. Looks like you're talking about a different subject. Would you mind opening a new issue and explain in detail what you're asking?

Thanks!
