### ISSUE TITLE
Invoking Gulp programmatically

### ISSUE THREAD

**Issue by samvv** [therealklanni/git-guppy#8]
I have filed an issue at gulpjs/gulp#770 about invoking Gulp programmatically in the current execution environment instead of spawning a new process.

This should provide a tiny boost in the hook execution speed, and make it possible to use other parts of the Gulp API.

It also should make way to fix issue #2 by asking Gulp if a task for the specified hook is defined.

**Comment by therealklanni** [comment]
I'm not sure this is relevant anymore.
