### ISSUE TITLE
commit not aborting

### ISSUE THREAD

**Issue by LucaVazz** [therealklanni/git-guppy#81]
Hey, I hae the following test - setup:
**./package.json** 
````
{
  "name": "guppy-test",
  "devDependencies": {
    "git-guppy": "^1.2.1",
    "gulp": "^3.9.1",
    "gulp-task-loader": "^1.2.1",
    "guppy-pre-commit": "^0.3.0"
  }
}
````
**./gulpfile.js**
````JavaScript
var gulp = require('gulp');
require('gulp-task-loader')('hooks_gulp-tasks');

gulp.task('pre-commit', ['rejector']);
````
**./hooks_gulp-tasks/rejector.js**
````JavaScript
var gulp = require('gulp');
var guppy = require('git-guppy')(gulp);

module.exports = function () {
  console.log("Nope, I'm rejecting ", guppy.src('pre-commit'), '!');

  return 1;
};
````

But every commit is just passing and completing without any trace of the `return 1`.

**Versions:**
````
λ node --version
v6.3.0
λ npm --version
3.10.3
λ gulp --version
[16:33:54] CLI version 1.2.1
[16:33:54] Local version 3.9.1
λ git --version
git version 2.9.0.windows.1
````

**Comment by therealklanni** [comment]
Was this working before? Did you upgrade guppy at some point and it stopped working after that? Or are you using guppy for the first time?

I would also need to see how the `pre-commit` condition is being triggered in your use-case. Are you staging a file to be committed and then trying to commit? Are you trying to commit without staging any files? Without more information, I can't really identify the problem you're having.

You may also want to look at the documentation to double check if what you're trying to do would actually trigger a pre-commit check.

**Comment by LucaVazz** [comment]
I'm trying out guppy for the fist time (and this was only intended fas a little test).



Yes, I'm staging a file and then try to commit. Here is the console-output of git:
````
D:\_Projects\git-hooks\guppy-test (master) (guppy-test@0.0.1)
λ git add .

D:\_Projects\git-hooks\guppy-test (master) (guppy-test@0.0.1)
λ git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   test.txt


D:\_Projects\git-hooks\guppy-test (master) (guppy-test@0.0.1)
λ git commit -m "foobar"
(node:16764) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[10:55:13] Using gulpfile D:\_Projects\git-hooks\guppy-test\gulpfile.js
[10:55:13] Starting 'rejector'...
Nope, I'm rejecting  [ 'test.txt' ] !
[10:55:14] Finished 'rejector' after 698 ms
[10:55:14] Starting 'pre-commit'...
[10:55:14] Finished 'pre-commit' after 92 μs
[master 2ac87a9] foobar
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test.txt
````



As I understand it, this should trigger the hook. And as can be seen by the output, it really does trigger it, but then its return-value is seemingly ignored.

**Comment by LucaVazz** [comment]
Interestingly, I can't get it to work at all on my Debian-machine:
````
root@gitlab:/home/luca/Desktop/guppy-test# cat > test_debian.txt
root@gitlab:/home/luca/Desktop/guppy-test# git add .
root@gitlab:/home/luca/Desktop/guppy-test# git commit -m "debian"
Error: spawn ENOENT
    at errnoException (child_process.js:1000:11)
    at Process.ChildProcess._handle.onexit (child_process.js:791:34)
[master 736ba10] debian
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test_debian.txt
root@gitlab:/home/luca/Desktop/guppy-test# 
````
It seems like `ENOENT` occurs while the `pre-commit`-file created by guppy tries to spawn the `pre-commit`-gulp-task...

**Comment by therealklanni** [comment]
You may need to have a pre-established project (at least one commit) for it to work. I don't know if I've ever tested it with a brand-new project.

**Comment by therealklanni** [comment]
```
[10:55:13] Starting 'rejector'...
Nope, I'm rejecting  [ 'test.txt' ] !
[10:55:14] Finished 'rejector' after 698 ms
[10:55:14] Starting 'pre-commit'...
[10:55:14] Finished 'pre-commit' after 92 μs
```

This is likely the problem. Basically the "rejector" task finishes (without error), and so pre-commit starts (does nothing) and then ends (without error). You might need to read up on how gulp works. It's based on streams, so you can't just `return 1` from the function, that won't do anything. Sorry I didn't notice this earlier.

**Comment by LucaVazz** [comment]
Oh... Sorry, my bad.

(Do you know about a better way in gulp to error correctly for this use-case than `PluginError` from `gulp-util` or would that be fitting?)

**Comment by therealklanni** [comment]
I would just use the gulp-util error method.
