### ISSUE TITLE
Problem with guppy pre-commit hook

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [therealklanni/git-guppy#82]
If I create fresh dir (like team city does) and try to install package guppy post action hangs

mkdir tmp
cd tmp
npm i guppy-pre-commit

this is critical for us because our CI stops.
this happens because there is no git folder yet.

Can you solve this asap?

**Comment by therealklanni** [comment]
You probably should do a `git init` before you do `npm i`. The hook wouldn't work anyway without git being initialized, and I'm not going to initialize git from guppy, it just wouldn't make sense to do so.

**Comment by vytautas-pranskunas-** [comment]
I think you should not do git init from guppy, but team city has nothing to do with pre commits too. So i think the right way to go be if you check if git folder exists and if not do nothing.

**Comment by therealklanni** [comment]
Are you using `npm i --production` in your CI? You might want to try that *first* (hopefully guppy packages are installed as *dev* dependencies). Let me know if that solves your issue, if not, open a new issue on [guppy-cli](https://github.com/therealklanni/guppy-cli) for "Show warning when git is not initialized" and we can discuss a possible solution for that.

**Comment by vytautas-pranskunas-** [comment]
Hi, i cannot do that because on CI is building dev env and running karma tests which are under dev dependency same as guppy. So i will create new issue. It will be great if you can solve this asap because our CI latest build is down for 48h already...
