### ISSUE TITLE
Option for silent mode

### ISSUE THREAD

**Issue by JefHellemans** [therealklanni/git-guppy#83]
Add an option so guppy can run gulp commands in `--silent` mode. This will allow for custom output and doesn't clutter your terminal with gulp messages when you don't need it to.

**Example code**
```
gulp.task('pre-commit', function () {
  return gulp.src(guppy.src('pre-commit',  ['--silent']))
    .pipe(gulpFilter(['*.js']))
    .pipe(jshint())
    .pipe(customReporter)
    .pipe(jshint.reporter('fail'));
});
```

**Example output**
```
~/user/project$ git commit -m "some commit"

Please don't commit JSHint errors!
* /project/file.js: line 10, col 25

Aborting commit...
```

**Instead of**
```
~/user/project$ git commit -m "some commit"
[09:02:22] Using gulpfile ~/user/project/gulpfile.js
[09:02:22] Starting 'pre-commit'...

Please don't commit JSHint errors!
* /project/file.js: line 10, col 25

Aborting commit...

[09:02:23] 'pre-commit' errored after 1.43 s
[09:02:23] Error in plugin 'gulp-jshint'
Message:
    JSHint failed for: assets/scripts/modules/insights/controller.js
```

This would help a lot in readability. I feel like it should be possible to add in the hook file somewhere? Not entirely sure of the setup here but it would be a great addition.

**Comment by therealklanni** [comment]
This is more likely a feature request for [gulp](https://github.com/gulpjs/gulp), not guppy. I don't control how gulp logs to the terminal.
