### ISSUE TITLE
Is it possible to interfere with git?

### ISSUE THREAD

**Issue by Burnett01** [therealklanni/git-guppy#96]
First of all, this is a well made system which I use a lot.

Now to my question:  Is it possible to add additional files to the commit in the guppy-pre-commit hook?

For example, I have the following hook:

```javascript
gulp.task('pre-commit', ['this_generates_two_files']);

gulp.task('this_generates_two_files', function() {
 // generate files
});
```
The question at hand is:

How do I add those generated files to the commit called in the guppy-pre-commit hook?

With a bare git-hook I would use a pre-commit hook and add the file to the commit:

```bash
#!/bin/sh
git add file.1
git add file.2
```

What I need is "access" to git while running the git-guppy-pre-commit hook.

**Comment by Burnett01** [comment]
Figured that I could use guppy in combination with the gulp-git module: https://github.com/stevelacy/gulp-git

```javascript
// Run git add with options
gulp.task('add', function(){
  return gulp.src('./git-test/*')
    .pipe(git.add({args: '-f -i -p'}));
});
```

Is this a proper solution? Thanks in advance.

**Comment by therealklanni** [comment]
That could work, though I haven't tried it myself. Were you able to figure it out?

**Comment by Burnett01** [comment]
Thank @therealklanni It works perfectly fine with your module in combi with git-gulp.
